osx_image: xcode9.2
language: node_js

env:
  global:
    - FORCE_COLOR=1

matrix:
  include:
    - os: osx
      env: TEST_FILES=BuildTest,extraMetadataTest,globTest,filesTest,ignoreTest,linux,windows
      node_js: "9"

    - os: osx
      env: TEST_FILES=CodeSignTest,macArchiveTest,macPackagerTest,macIconTest
      node_js: "9"

    - os: osx
      env: TEST_FILES=masTest,dmgTest
      node_js: "9"

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/Library/Caches/electron
    - $HOME/Library/Caches/electron-builder
    - /tmp/jest-electron-builder-tests

install:
  - curl -L https://yarnpkg.com/latest.tar.gz | tar xz && mv yarn-* $HOME/.yarn
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn

script:
  - yarn test

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"